# 端口号
server:
  port: 80

#配置数据源 data-username 会出错，必须使用username
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    initial-size: 5

